# Linear Combination

In this notebook I aim to learn how to solve combination problems using the python package [NumPy](https://www.numpy.org/) and it's linear algebra subpackage [linalg](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html). This lab is supposed to prepare me for the linear algebra that I'll use in Neural Networks.

## Determining a Vector's span

A vector's span is the set of all prossible vectors that you can reach with a linear combination of a given pair of vectors.
Given vectors $\vec{v}$ and $\vec{w}$, a third vector $\vec{t}$ is within their span if $\vec{t}$ can be written as a linear combination of the pair $\vec{v}$ and $\vec{w}$.

This can be written as:

$\hspace{1cm}a\vec{v} + b\vec{w} = \vec{t}$

$\hspace{1.2cm}$*Equation 1*

This means, that if I can find a set of values for the scalars $a$ and $b$ that make *Equation 1* true, then $\vec{t}$ is within the span of $\vec{v}$ and $\vec{w}$.


Let:

$\hspace{1cm}\vec{v} = \begin{bmatrix} 1\\ 3\end{bmatrix}$
$\hspace{0.3cm}\vec{w} = \begin{bmatrix} 2\\ 5\end{bmatrix}$ 
$\hspace{0.3cm}\vec{t} = \begin{bmatrix} 4\\ 11\end{bmatrix}$

We can rewrite $a\vec{v} + b\vec{w} = \vec{t}$ as:

$\hspace{1cm}a\begin{bmatrix} 1\\ 3\end{bmatrix} + b\begin{bmatrix} 2\\ 5\end{bmatrix} = \begin{bmatrix} 4\\ 11\end{bmatrix}$

Re-writing *Equation 1* as an augmented matrix gives:

$\hspace{1cm}
\left[
\begin{array}{cc|c}
1 & 2 & 4\\
3 & 5 & 11
\end{array}
\right]
$

## Determining the span computationally

1. Make [NumPy](https://www.numpy.org/) Python package available using the import method
2. Create right and left sides of the augmented matrix:
   1. Create a [NumPy vector](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.creation.html) $\vec{t}$ to represent the right side of the augmented matrix.
   2. Create a [NumPy matrix](https://docs.scipy.org/doc/numpy-.13.0/user/basics.creation.html) named $vw$ that represents the left side of the augmented matrix ($\vec{v}$ and $\vec{w}_
   3. Use NumPy's [**linalg.solve** function](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.solve.html#numpy.linalg.solve) to check a vector's span computationally by solving for the scalers that make toe equation true.

I shall define the function *__check_vector_span__* for this task.


In [19]:
# Makes Python package NumPy available using import method
import numpy as np

# Creates matrix t (right side of the augmented matrix).
t = np.array([4, 11])

# Creates matrix vw (left side of the augmented matrix).
vw = np.array([[1, 2], [3, 5]])

# Prints vw and t
print("\nMatrix vw:", vw, "\nVector t:", t, sep="\n")



Matrix vw:
[[1 2]
 [3 5]]

Vector t:
[ 4 11]


In [20]:
def check_vector_span(set_of_vectors, vector_to_check):
    """
    Checks if vector_to_check is in the span of the vectors in the set of vectors.
    Args:
        set_of_vectors (np.array): Set of vectors being considered.
        vector_to_check (np.array): Vector to be checked.
    Returns:
        Vector of scalers that solves the linear equation.
    """
    # Shaping the output vector correctly
    vector_of_scalars = np.asarray([None]*set_of_vectors.shape[0])

    # Finding the scalars that solve the equation (if vector is within the span)
    try:
        vector_of_scalars = np.linalg.solve(set_of_vectors, vector_to_check)
        if vector_of_scalars is not None:
            print("\nVector is within span.\nScalars in s:", vector_of_scalars)
    # If vector is not within the span
    except Exception as e:
        if str(e) == "Singular matrix":
            print("\nNo single solution\nVector is NOT within span")
        else:
            print("\nUnexpected Exception Error:", e)
    return vector_of_scalars
    

## Checking *check_vector_span* by solving for Scalars

*Notice that:*

 - There are two more sets of vectors that are being checked.
The second set of vectors have the following values and augmented matrix:

$\hspace{1cm}
\vec{v2} = \begin{bmatrix} 1\\ 2\end{bmatrix}
\hspace{0.3cm}\vec{w2} = \begin{bmatrix} 2\\ 4\end{bmatrix}
\hspace{0.3cm}\vec{t2} = \begin{bmatrix} 6\\ 12\end{bmatrix}
\hspace{1cm}
\left[\begin{array}{cc|c}
1 & 2 & 6\\
2 & 4 & 12\\
\end{array}\right]$

The third set of vectors have the following values and augmented matrix:

$\hspace{1cm}
\vec{v3} = \begin{bmatrix} 1\\ 1\end{bmatrix}
\hspace{0.3cm}\vec{w3} = \begin{bmatrix} 2\\ 2\end{bmatrix}
\hspace{0.3cm}\vec{t3} = \begin{bmatrix} 6\\ 10\end{bmatrix}
\hspace{1cm}
\left[\begin{array}{cc|c}
1 & 2 & 6\\
1 & 2 & 10
\end{array}\right]$

The Python code below uses these inputs to test the function created in the cell  above.

In [21]:
# Calling check_vector_span to check vectors in Equation 1
print(f"\nEquation 1:\n Matrix vw: \n{vw}\nVector t: \n{t}", sep='\n')
s = check_vector_span(vw, t)
print(s)

# Call to check a new set of vectors vw2 and t2
vw2 = np.array([[1, 2], [2, 4]])
t2 = np.array([6, 12])
print(f"\nEquation 2:\n Matrix vw2:\n{vw2}\nVector t:\n{t2}", sep='\n')
s2 = check_vector_span(vw2, t2)
print(s2)

# Call to check a new set of vectors vw3 and t3
vw3 = np.array([[1, 1], [2, 2]])
t3 = np.array([6, 10])
print(f"\nEquation 3:\n Matrix vw3:\n{vw3}\nVector t:\n{t3}", sep='\n')
s3 = check_vector_span(vw3, t3)
print(s3)


Equation 1:
 Matrix vw: 
[[1 2]
 [3 5]]
Vector t: 
[ 4 11]

Vector is within span.
Scalars in s: [2. 1.]
[2. 1.]

Equation 2:
 Matrix vw2:
[[1 2]
 [2 4]]
Vector t:
[ 6 12]

No single solution
Vector is NOT within span
[None None]

Equation 3:
 Matrix vw3:
[[1 1]
 [2 2]]
Vector t:
[ 6 10]

No single solution
Vector is NOT within span
[None None]
